basically finished rs_manager

diff --git a/rs_manager b/rs_manager
--- a/rs_manager
+++ b/rs_manager
@@ -4,7 +4,6 @@
 i_flag='' #install RustDedicated
 u_flag='' #update 
 r_flag='' #run
-v_flag='' #validate install
 o_flag='' #install oxide (uMod)
 h_flag='' #print help
 
@@ -14,8 +13,7 @@ print_usage() {
     echo "  -i (--install) install Rust server"
     echo "  -u (--update) update Rust server"
     echo "  -r (--run) run Rust server"
-    echo "  -v (--validate) validate install"
-    echo "  -o (--oxide) install Oxide (uMod)"
+    echo "  -o (--oxide) install or update Oxide (uMod)"
     echo "  -h (--help) print help"
     echo ""
 }
@@ -52,7 +50,7 @@ done
 if [[ $i_flag == 'true' ]] ; then
     space "Installing Rust server."
 
-    mkdir SteamCMD 
+    mkdir SteamCMD || error "Seems that SteamCMD is already installed. If you want to install it anyway delete SteamCMD directory." 
     cd SteamCMD 
     wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" || error "Failed to download SteamCMD."
     tar -vzxf steamcmd_linux.tar.gz || error "Failed to extract the archive."
@@ -61,18 +59,42 @@ if [[ $i_flag == 'true' ]] ; then
     
     cd ..
 
+    echo './RustDedicated +server.port 28015 +server.level "Procedural Map" +server.seed 1234 +server.worldsize 4000 +server.maxplayers 25 +server.hostname "Server name" +server.description "Server description" +rcon.port 28016 +rcon.password changeitplease' > start.sh
+    chmod +x start.sh
+
     space "Installed succesfully."
 fi
-
-
 if [[ $u_flag == 'true' ]] ; then
     space "Updating Rust server."
 
-    cd SteamCMD || error "Seems that server isn't installed, make sure to run ./rs_manager -i before updating."
+    cd SteamCMD || error "Seems that server isn't installed, make sure to install it first."
     ./steamcmd.sh +login anonymous +force_install_dir .. +app_update 258550 validate +quit
     cd ..
 
-    space "Updated succesfully."
+    echo " "
 fi
+
+
+if [[ $r_flag == 'true' ]] ; then
+    space "Starting server."
+
+    cat start.sh || error 'start.sh file not found. '
+
+    tmux new-session -d -s rustserver './start.sh' || error "Tmux not found, make sure to install tmux before starting the server."
+    tmux a
+fi
+
+
+if [[ $o_flag == 'true' ]] ; then
+    space "Installing oxide."
+
+    wget "https://umod.org/games/rust/download/develop" || error "Failed to download Oxide." 
+    mv develop oxide.zip
+    echo " "
+    unzip -o oxide.zip
+
+    space "Oxide installed succesfully."
+fi
+
 
 exit 0
